# Write a program to generate a Fibonacci series of numbers.
# Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
# Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
#   a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
#   b) Generate the series until the element in the series is less than Max number.


a = 0
b = 1
n = int(input("Enter a number: "))
c = 0
i = 1

# operation (a)
while(i<=n):
    print(a)
    c = a+b
    a = b
    b = c
    i = i+1

# operation (b)
j = 1
x = 0
y = 1
z = 0
while(j<=n):
    if(x<n):
        print(x)
        z = x + y
        x = y
        y = z
        j = j+1
    else:
        break
